version: '3.1'

services:
  iot-frontend:
    image: iot-frontend:test
    container_name: iot-frontend
    ports:
      - '80:3000'
  iot-api:
    image: iot-api:test
    container_name: iot-api
    environment:
      - API_URL=http://localhost:4000/
    ports:
      - '4000:4000'
    volumes:
      - img:/img
    networks:
      - iot-net
  iot-db:
    image: iot-db:test
    container_name: iot-db
    environment:
      - MONGO_INITDB_DATABASE=application
    volumes:
      - database:/data/db
    networks:
      - iot-net

networks:
  iot-net:

volumes:
  img:
  database:
