version: '3.1'

services:
  iot-frontend:
    image: prodalia/iot-frontend
    container_name: iot-frontend
    environment:
      - API_URL=http://iot-db:27017
      - NODE_ENV=production
    ports:
      - '3000:3000'
    networks:
      - iot-net
  iot-api:
    image: prodalia/iot-api
    container_name: iot-api
    environment:
      - MONGO_ENV=local
      - API_URL=http://iot-db:27017
      - NODE_ENV=production
    ports:
      - '4000:4000'
    volume:
      - img:/img
    networks:
      - iot-net
  iot-db:
    image: prodalia/iot-db
    container_name: iot-db
    environment:
      - MONGO_INITDB_DATABASE=application
    ports:
      - '27017:27017'
    volume:
      - database:/data/db
    networks:
      - iot-net

networks:
  iot-net:
